// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrtovhqequmhdgccwffs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydG92aHFlcXVtaGRnY2N3ZmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDAxMzEsImV4cCI6MjA3NDIxNjEzMX0.iMIFLvg0l1i5xbQexSM2rkYlJWZ1bxiDpx3_6cxGINg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});